xLogs.RegisterCategory("Keypads", "Other")
xLogs.RegisterCategory("pVault", "Other")
xLogs.RegisterCategory("Ticket Book", "Other")
xLogs.RegisterCategory("Tier Printer", "Other")
xLogs.RegisterCategory("xAdmin", "Other")
xLogs.RegisterCategory("bComms", "Other")

hook.Add("keypad_access_granted", "xLogsOther-KeyPad", function(ent, ply)
	xLogs.Log(xLogs.Core.Player(ply).." successfully entered keypad code on "..xLogs.Core.Player(ent:CPPIGetOwner()).."'s keypad", "Keypads")
end)
hook.Add("keypad_cracked", "xLogsOther-KeyPad", function(ent, ply)
	xLogs.Log(xLogs.Core.Player(ply).." successfully cracked "..xLogs.Core.Player(ent:CPPIGetOwner()).."'s keypad", "Keypads")
end)



hook.Add("TicketBookSendTicket", "xLogsTicketBook", function(ply, target, amount)
	xLogs.Log(xLogs.Core.Player(ply).." has given "..xLogs.Core.Player(target).." a ticket for "..xLogs.Core.Color(DarkRP.formatMoney(amount), Color(0, 200, 0)), "Ticket Book")
end)
hook.Add("TicketBookDenyTicket", "xLogsTicketBook", function(ply, target)
	xLogs.Log(xLogs.Core.Player(ply).." has denied "..xLogs.Core.Player(target).."'s ticket", "Ticket Book")
end)
hook.Add("TicketBookPayTicket", "xLogsTicketBook", function(ply, target)
	xLogs.Log(xLogs.Core.Player(ply).." has paid "..xLogs.Core.Player(target).."'s ticket", "Ticket Book")
end)

hook.Add("TierPrinterDestroy", "xLogsOwain-TierPrinter", function(ply)
	xLogs.Log(xLogs.Core.Player(ply).."'s printer was destroyed", "Tier Printer")
end)
hook.Add("TierPrinterRecharge", "xLogsOwain-TierPrinter", function(ply)
	xLogs.Log(xLogs.Core.Player(ply).."'s printer was recharged", "Tier Printer")
end)
hook.Add("TierPrinterUpgrade", "xLogsOwain-TierPrinter", function(target, tier, ply)
	xLogs.Log(xLogs.Core.Player(target).."'s printer was upgraded to tier "..xLogs.Core.Color(DarkRP.formatMoney(tier), Color(0, 0, 200)).." by "..xLogs.Core.Player(ply), "Tier Printer")
end)
hook.Add("TierPrinterWithdraw", "xLogsOwain-TierPrinter", function(target, money, ply)
	xLogs.Log(xLogs.Core.Player(target).."'s printer had a withdrawal of "..money.." by "..xLogs.Core.Player(ply), "Tier Printer")
end)



hook.Add("pVaultMoneyCleaned", "xLogsOwain-pVault", function(ply, money)
	xLogs.Log(xLogs.Core.Player(ply).." has cleaned "..xLogs.Core.Color(DarkRP.formatMoney(money), Color(0, 200, 0)), "pVault")
end)
hook.Add("pVaultVaultCracked", "xLogsOwain-pVault", function(ent, ply)
	xLogs.Log(xLogs.Core.Player(ply).." has cracked a vault!", "pVault")
end)
hook.Add("pVaultVaultCrackFailed", "xLogsOwain-pVault", function(ent, ply)
	xLogs.Log(xLogs.Core.Player(ply).." has failed to crack a vault...", "pVault")
end)