-- All the net messages defined here
util.AddNetworkString("xStore")
util.AddNetworkString("xStoreOpenMenu")
util.AddNetworkString("xStoreRefreshCredits")
util.AddNetworkString("xStoreRefreshCreditsReturn")
util.AddNetworkString("xStorePurchaseItem")
util.AddNetworkString("xStoreToggleItem")
util.AddNetworkString("xStoreCreateListing")
util.AddNetworkString("xStorePurchaseListing")
util.AddNetworkString("xStoreRemoveListing")
util.AddNetworkString("xStoreCreateClass")
util.AddNetworkString("xStoreEditClass")
util.AddNetworkString("xStoreGiveClassAccess")
util.AddNetworkString("xStoreRemoveClassAccess")
util.AddNetworkString("xStoreActiveClass")