-- All the net messages defined here
util.AddNetworkString("xyz_partner_open")
util.AddNetworkString("xyz_partners_open")
util.AddNetworkString("xyz_partner_open_higher")
util.AddNetworkString("xyz_partner_request")
util.AddNetworkString("xyz_partner_request_send")
util.AddNetworkString("xyz_partner_request_accept")
util.AddNetworkString("xyz_partner_request_deny")
util.AddNetworkString("xyz_partner_request_force")
util.AddNetworkString("xyz_partner_data")
util.AddNetworkString("xyz_partner_data_remove")