CustomizableWeaponry:addFireSound("KM60_FIRE", {"weapons/SlaYeR's M60/fire1.wav","weapons/SlaYeR's M60/fire2.wav","weapons/SlaYeR's M60/fire3.wav"}, 1, 125, CHAN_STATIC)
CustomizableWeaponry:addFireSound("KM60_FIRE_SUPPRESSED", {"weapons/SlaYeR's M60/firesil1.wav","weapons/SlaYeR's M60/firesil2.wav","weapons/SlaYeR's M60/firesil3.wav"}, 1, 65, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("KM60.Bolt", "weapons/SlaYeR's M60/Bolt.wav")
CustomizableWeaponry:addReloadSound("KM60.CoverUp", "weapons/SlaYeR's M60/CoverUp.wav")
CustomizableWeaponry:addReloadSound("KM60.Boxout", "weapons/SlaYeR's M60/BoxOut.wav")
CustomizableWeaponry:addReloadSound("KM60.Chain", "weapons/SlaYeR's M60/Chain.wav")
CustomizableWeaponry:addReloadSound("KM60.Boxin", "weapons/SlaYeR's M60/BoxIn.wav")
CustomizableWeaponry:addReloadSound("KM60.CoverDown", "weapons/SlaYeR's M60/CoverDown.wav")
CustomizableWeaponry:addReloadSound("KM60.Draw", "weapons/SlaYeR's M60/Deploy.wav")