-- All the net messages defined here
util.AddNetworkString("EventSystem:UI:Admin")
util.AddNetworkString("EventSystem:UI:Admin:CreateEvent")
util.AddNetworkString("EventSystem:UI:Admin:CreateEvent:Start")
util.AddNetworkString("EventSystem:UI:Admin:RequestData")
util.AddNetworkString("EventSystem:UI:Admin:SendAction")
util.AddNetworkString("EventSystem:Invite")
util.AddNetworkString("EventSystem:Invite:Accept")
util.AddNetworkString("EventSystem:TeamMembers")
util.AddNetworkString("EventSystem:SendSpawnPoints")
util.AddNetworkString("EventSystem:UI:Admin:AddSpawnPoint")
util.AddNetworkString("EventSystem:UI:Admin:RemoveSpawnPoint")
util.AddNetworkString("EventSystem:UI:Admin:WipeSpawnPoint")
util.AddNetworkString("EventSystem:UI:Admin:SpawnEntity")
util.AddNetworkString("EventSystem:Message")
util.AddNetworkString("EventSystem:UI:Admin:EndEvent")