CustomizableWeaponry:addFireSound("VERESK_FIRE", {"weapons/sr2/fire1.wav", "weapons/sr2/fire2.wav", "weapons/sr2/fire3.wav"}, 1, 125, CHAN_STATIC)
CustomizableWeaponry:addFireSound("VERESK_SUPFIRE", {"weapons/sr2/firesup1.wav", "weapons/sr2/firesup2.wav", "weapons/sr2/firesup3.wav"}, 1, 60, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("VERESK_BOLTREL", "weapons/sr2/boltrelease.wav")
CustomizableWeaponry:addReloadSound("VERESK_MAGOUT", "weapons/sr2/magout.wav")
CustomizableWeaponry:addReloadSound("VERESK_MAGIN", "weapons/sr2/magin.wav")
CustomizableWeaponry:addReloadSound("VERESK_MAGIN2", "weapons/sr2/magin2.wav")
CustomizableWeaponry:addReloadSound("VERESK_MAGDRAW", "weapons/sr2/magdraw.wav")
CustomizableWeaponry:addReloadSound("VERESK_FOREGRIP", "weapons/sr2/foregrip.wav")
CustomizableWeaponry:addReloadSound("VERESK_HANDLE", "weapons/sr2/handle.wav")