CustomizableWeaponry:addFireSound("CW_M249_OFFICIAL_FIRE", "weapons/cw_m249/fire.wav", 1, 112, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_M249_OFFICIAL_FIRE_SUPPRESSED", "weapons/cw_m249/fire_suppressed3.wav", 1, 95, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_BOLTBACK", "weapons/cw_m249/boltback.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_BOLTRELEASE", "weapons/cw_m249/boltrelease.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_BULLETIN", "weapons/cw_m249/bulletin.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_COVERCLOSE", "weapons/cw_m249/coverclose.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_COVEROPEN", "weapons/cw_m249/coveropen.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_MAGDRAW", "weapons/cw_m249/magdraw.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_MAGIN", "weapons/cw_m249/magin.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_MAGOUT", "weapons/cw_m249/magout.wav")
CustomizableWeaponry:addReloadSound("CW_M249_OFFICIAL_MAGOUT_FULL", "weapons/cw_m249/magoutfull.wav")