hook.Add("PlayerInitialSpawn", "xyz_chat_ply_connect", function(ply)
	net.Start("xyz_chat_connection")
		net.WriteString(ply:Name())
		net.WriteBool(true)
	net.Broadcast()
end)
hook.Add("PlayerDisconnected", "xyz_chat_ply_disconnect", function(ply)
	net.Start("xyz_chat_connection")
		net.WriteString(ply:Name())
		net.WriteBool(false)
		net.WriteString(ply:SteamID())
		net.WriteColor(team.GetColor(ply:Team()))
	net.Broadcast()
end)