net.Receive("Impound:UI:Impound", function()
	local vehicleID = net.ReadUInt(32)
	XYZUI.Confirm("Unimpound for "..DarkRP.formatMoney(Impound.Config.ImpoundFee), Impound.Config.Color, function()
		net.Start("Impound:Unimpound")
			net.WriteUInt(vehicleID, 32)
		net.SendToServer()
	end)
end)
net.Receive("Impound:UI:Clamp", function()
	local vehicle = net.ReadEntity()
	local price = net.ReadUInt(32)
	
	XYZUI.Confirm("Unclamp for "..DarkRP.formatMoney(price), Impound.Config.Color, function()
		net.Start("Impound:Unclamp")
			net.WriteEntity(vehicle)
		net.SendToServer()
	end)
end)