-- All the net messages defined here
util.AddNetworkString("CarDealer:UI")
util.AddNetworkString("CarDealer:UI:Return")
util.AddNetworkString("CarDealer:UI:Repair")
util.AddNetworkString("CarDealer:Purchase")
util.AddNetworkString("CarDealer:Tune")
util.AddNetworkString("CarDealer:Spawn")
util.AddNetworkString("CarDealer:Sell")
util.AddNetworkString("CarDealer:Return")
util.AddNetworkString("CarDealer:Vehicle:Load")
util.AddNetworkString("CarDealer:Vehicle:New")
util.AddNetworkString("CarDealer:Vehicle:Update")
util.AddNetworkString("CarDealer:Vehicle:Remove")
util.AddNetworkString("CarDealer:Vehicle:Repair")