CustomizableWeaponry:addFireSound("KHRPKM_FIRE", {"weapons/PKM/fire1.wav","weapons/PKM/fire2.wav","weapons/PKM/fire3.wav"}, 1, 125, CHAN_STATIC)
CustomizableWeaponry:addFireSound("KHRPKM_FIRE_SUPPRESSED", {"weapons/PKM/firesil2.wav","weapons/PKM/firesil3.wav"}, 1, 65, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("KHRPKM.Coverup", "weapons/PKM/pkm_coverup.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Bullet", "weapons/PKM/pkm_bullet.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Chain", "weapons/PKM/pkm_chain.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Boxout", "weapons/PKM/pkm_boxout.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Boxin", "weapons/PKM/pkm_boxin.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Coverdown", "weapons/PKM/pkm_coverdown.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Coversmack", "weapons/PKM/pkm_coversmack.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Bolt", "weapons/PKM/pkm_bolt.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Cloth", "weapons/PKM/pkm_cloth.wav")
CustomizableWeaponry:addReloadSound("KHRPKM.Draw", "weapons/PKM/pkm_draw.wav")