resource.AddFile("materials/swb/bullet.vmt")
resource.AddFile("materials/swb/clumpspread_ring.vmt")
resource.AddFile("materials/swb/scope_rifle.vmt")
resource.AddFile("materials/swb_muzzle/flash.vmt")
resource.AddFile("materials/swb_muzzle/flash_rif.vmt")
resource.AddFile("materials/swb_muzzle/flash_spark.vmt")
resource.AddFile("particles/swb_muzzle.pcf")