-- All the net messages defined here
util.AddNetworkString("xAdminNetworkIDRank")
util.AddNetworkString("xAdminNetworkExistingUsers")
util.AddNetworkString("xAdminNetworkCommands")
util.AddNetworkString("xAdminAFKCheck")
util.AddNetworkString("xAdminAFKConfirm")
util.AddNetworkString("xAdminChatMessage")
util.AddNetworkString("xAdminSpectate")
util.AddNetworkString("xAdminStartAnnouncement")
util.AddNetworkString("xAdminKnownAliases")
util.AddNetworkString("xAdminScanHit")
util.AddNetworkString("xAdminRequestAlts")
util.AddNetworkString("xAdminRequestFriends")
util.AddNetworkString("xAdminRequestFocus")