CustomizableWeaponry:addFireSound("CW_SV98_FIRE", "weapons/sv98/shootnew.wav", 1, 140, CHAN_STATIC)
CustomizableWeaponry:addFireSound("CW_SV98_FIRE_SUPPRESSED", "weapons/sv98/firesuppnew.wav", 1, 105, CHAN_STATIC)

CustomizableWeaponry:addReloadSound("CW_SV98_MAGOUT", "weapons/sv98/clipout.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_MAGIN", "weapons/sv98/clipin.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_BOLTUP", "weapons/sv98/boltpush.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_LATCH", "weapons/sv98/reeloadlatch.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_BOLTDOWN", "weapons/sv98/boltlock.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_BOLTPULL", "weapons/sv98/boltback.wav")
CustomizableWeaponry:addReloadSound("CW_SV98_BOLTPUSH", "weapons/sv98/boltpush.wav")
