-- All the net messages defined here
util.AddNetworkString("xyz_orgs_menu")
util.AddNetworkString("xyz_orgs_join")
util.AddNetworkString("xyz_orgs_create")
util.AddNetworkString("xyz_orgs_deposit")
util.AddNetworkString("xyz_orgs_withdraw")
util.AddNetworkString("xyz_orgs_disband")
util.AddNetworkString("xyz_orgs_updatemember")
util.AddNetworkString("xyz_orgs_discipline")
util.AddNetworkString("xyz_orgs_upgrade")
util.AddNetworkString("xyz_orgs_info")
util.AddNetworkString("xyz_orgs_withdraw_inv")
util.AddNetworkString("xyz_orgs_managerole")
util.AddNetworkString("xyz_orgs_createrole")
util.AddNetworkString("xyz_orgs_leave")
util.AddNetworkString("xyz_orgs_transfer")